/**
 * GymProof private state and witnesses.
 *
 * Mirrors the structure of the reference bboard `witnesses.ts`: the private
 * state object is owned by the DApp and injected into circuits through
 * witness functions. None of these values are ever written to the ledger.
 */
import type { WitnessContext } from "@midnight-ntwrk/midnight-js-protocol/compact-runtime";
// Generated by `npm run compact`. Present only after the Compact compiler runs.
import type { Ledger } from "./managed/gymproof/contract/index.js";

/** A single privately logged workout. Never leaves the device. */
export type PrivateWorkout = {
  readonly id: string;
  /** epoch millis */
  readonly date: number;
  readonly durationMinutes: number;
  /** heaviest single-set load in kg across the session */
  readonly bestLiftKg: number;
};

export type GymProofPrivateState = {
  readonly secretKey: Uint8Array;
  readonly workouts: readonly PrivateWorkout[];
  /** challengeId (hex) -> window start/end in epoch millis */
  readonly challengeWindows: Readonly<Record<string, { start: number; end: number }>>;
};

export const createGymProofPrivateState = (
  secretKey: Uint8Array,
  workouts: readonly PrivateWorkout[] = [],
  challengeWindows: Readonly<Record<string, { start: number; end: number }>> = {},
): GymProofPrivateState => ({ secretKey, workouts, challengeWindows });

const toHexKey = (bytes: Uint8Array): string =>
  Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");

export const countWorkoutsInWindow = (
  state: GymProofPrivateState,
  challengeIdHex: string,
): number => {
  const window = state.challengeWindows[challengeIdHex];
  if (!window) return 0;
  return state.workouts.filter((w) => w.date >= window.start && w.date <= window.end).length;
};

export const computeLongestStreak = (state: GymProofPrivateState): number => {
  const days = Array.from(
    new Set(state.workouts.map((w) => Math.floor(w.date / 86_400_000))),
  ).sort((a, b) => a - b);
  let best = 0;
  let run = 0;
  let prev: number | undefined;
  for (const day of days) {
    run = prev !== undefined && day === prev + 1 ? run + 1 : 1;
    prev = day;
    if (run > best) best = run;
  }
  return best;
};

export const computeBestLiftKg = (state: GymProofPrivateState): number =>
  state.workouts.reduce((max, w) => (w.bestLiftKg > max ? w.bestLiftKg : max), 0);

export const witnesses = {
  localSecretKey: ({
    privateState,
  }: WitnessContext<Ledger, GymProofPrivateState>): [GymProofPrivateState, Uint8Array] => [
    privateState,
    privateState.secretKey,
  ],

  workoutsInWindow: (
    { privateState }: WitnessContext<Ledger, GymProofPrivateState>,
    challengeId: Uint8Array,
  ): [GymProofPrivateState, bigint] => [
    privateState,
    BigInt(countWorkoutsInWindow(privateState, toHexKey(challengeId))),
  ],

  longestStreak: ({
    privateState,
  }: WitnessContext<Ledger, GymProofPrivateState>): [GymProofPrivateState, bigint] => [
    privateState,
    BigInt(computeLongestStreak(privateState)),
  ],

  bestLiftKg: ({
    privateState,
  }: WitnessContext<Ledger, GymProofPrivateState>): [GymProofPrivateState, bigint] => [
    privateState,
    BigInt(computeBestLiftKg(privateState)),
  ],
};
